
name: render-specs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Render
        run: |
          npm install
          node -e "require('spec-up')({ nowatch: true })"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: .
